apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
  labels:
    app: binarycalculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
      - name: binarycalculator-app
        image: northamerica-northeast2-docker.pkg.dev/project-391b6111-4b6e-4bba-baa/sofe3980uu/binarycalculator:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: binarycalculator-service
spec:
  type: LoadBalancer
  selector:
    app: binarycalculator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080